In [2]:
import pandas as pd
import numpy as np

In [8]:
#creating a dataframe
df = pd.DataFrame(np.arange(0,20).reshape(4,5), index=['row1','row2','row3','row4'], columns=['col1','col2','col3','col4','col5'])
df

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19

In [14]:
#Accessing the elements using .loc
df.loc['row1']

col1    0
col2    1
col3    2
col4    3
col5    4
Name: row1, dtype: int32

In [18]:
type(df.loc['row1'])

pandas.core.series.Series

In [17]:
#Accessing the elements using .iloc
df.iloc[0:2,1:3]

col2  col3
row1     1     2
row2     6     7

In [19]:
type(df.iloc[0:2,1:3])

pandas.core.frame.DataFrame

In [30]:
#converting the pandas elements into list
df.iloc[0:2,0:2].values

array([[0, 1],
       [5, 6]])

In [31]:
df.loc['row2'].values

array([5, 6, 7, 8, 9])

In [34]:
#counting the values in column 'col1'
df['col1'].value_counts()

15    1
5     1
10    1
0     1
Name: col1, dtype: int64

In [36]:
df['col1'].unique()

array([ 0,  5, 10, 15])

In [39]:
#checking the null value in a dataframe
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
col5    0
dtype: int64